version: '3.5'

volumes:
  data:


services:
  database:
    image: 'postgres:latest'

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB:  default_database
      volumes:
        -data:/var/lib/postgres/data
      